
title: SFFA Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sci-fi-fantasy-alliance.github.io/

aux_links:
  Template Repository: https://github.com/Sci-Fi-Fantasy-Alliance/Sci-Fi-Fantasy-Alliance.github.io