
title: SFFA Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
url: https://sci-fi-fantasy-alliance.github.io/

markdown: kramdown

permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-spaceship

relative_links:
  enabled: true #default (true)
  collections: true #default (false)


aux_links:
  "Site Repository": https://github.com/Sci-Fi-Fantasy-Alliance/Sci-Fi-Fantasy-Alliance.github.io

remote_theme: Sci-Fi-Fantasy-Alliance/just-the-docs